import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004395",
        "surface-container-low": "#131b2e",
        "surface-dim": "#0b1326",
        surface: "#0b1326",
        "on-primary-container": "#340080",
        "on-primary-fixed": "#23005c",
        primary: "#d0bcff",
        "on-primary": "#3c0091",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#ca801e",
        "error-container": "#93000a",
        "primary-container": "#a078ff",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#ffb869",
        "on-error": "#690005",
        "inverse-surface": "#dae2fd",
        "outline-variant": "#494454",
        "tertiary-fixed": "#ffdcbb",
        "secondary-container": "#0566d9",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#482900",
        "secondary-fixed": "#d8e2ff",
        "on-secondary-container": "#e6ecff",
        "surface-tint": "#d0bcff",
        "primary-fixed": "#e9ddff",
        "on-tertiary-fixed": "#2c1700",
        "surface-container-high": "#222a3d",
        outline: "#958ea0",
        "on-tertiary-container": "#3f2300",
        "on-background": "#dae2fd",
        secondary: "#adc6ff",
        tertiary: "#ffb869",
        "primary-fixed-dim": "#d0bcff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-fixed": "#001a42",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed-variant": "#673d00",
        "surface-container-highest": "#2d3449",
        background: "#0b1326",
        "surface-container": "#171f33",
        "inverse-on-surface": "#283044",
        "on-secondary": "#002e6a",
        "on-primary-fixed-variant": "#5516be",
        "on-surface-variant": "#cbc3d7",
        "inverse-primary": "#6d3bd7",
        "on-surface": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-desktop": "40px",
        "stack-xl": "64px",
      },
      fontFamily: {
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-xl-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
