# Generated by Django 5.2.15 on 2026-06-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the event title.', max_length=200)),
                ('date_text', models.CharField(help_text='Format: JULY 5, 2026', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional breakdown text.', null=True)),
                ('venue', models.CharField(blank=True, help_text="Leave blank to automatically show 'TBA'.", max_length=250, null=True)),
                ('is_live', models.BooleanField(default=False, help_text='Check if this event is currently active/live.')),
            ],
        ),
    ]
