# Generated by Django 5.2.15 on 2026-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_event_date_text_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Paste the external URL (Luma, Unstop, Govao.ai, etc.)', max_length=500, null=True),
        ),
    ]
