# Generated by Django 5.2.15 on 2026-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the event title.', max_length=200)),
                ('date', models.DateTimeField(help_text='Select the date and time of the event.')),
                ('description', models.TextField(blank=True, help_text='Optional breakdown text.', null=True)),
                ('venue', models.CharField(blank=True, help_text="Leave blank to automatically show 'TBA'.", max_length=250, null=True)),
                ('registration_link', models.URLField(blank=True, help_text='Paste the external URL (Luma, Unstop, Govao.ai, etc.)', max_length=500, null=True)),
                ('is_live', models.BooleanField(default=False, help_text='Check if this event is currently active/live.')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the team member's full name.", max_length=100)),
                ('role', models.CharField(help_text="Enter the team member's role or position.", max_length=100)),
                ('tag', models.CharField(blank=True, help_text="A short title or designation (e.g., 'Lead Developer').", max_length=200, null=True)),
                ('bio', models.TextField(blank=True, help_text='A brief biography or description of the team member.', null=True)),
                ('image_url', models.CharField(blank=True, help_text='e.g., /team/ismail.jpeg', max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=300, null=True)),
                ('x_url', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
